## Uncomment the poll configuration section here and in the service `environment:` section if you want to enable polling of a repository.
x-poll-config: &poll-config
 POLL_CONFIG: |
   - url: https://github.com/pcs3rd/stickpile_compose-config.git  # This is the repository to poll
     reference: prod  # Optional: specify the branch or tag to poll, defaults to 'main'
     interval: 3003153600000  # Optional: specify the interval in seconds to poll the repository, defaults to 180 seconds (3 minutes)
     target: "us-east-stickpile-prod"  # Optional: use to target a specific deployment config file, e.g., "test" -> .doco-cd.test.yaml

services:
  doco-cd:
    #container_name: doco-cd
    # You can also pin to a specific tag (version)
    # Available tags can be found here: https://github.com/kimdre/doco-cd/pkgs/container/doco-cd
    image: ghcr.io/kimdre/doco-cd:0.57.0
    restart: unless-stopped
    ports:
      #- "80:80" # Webhook endpoint
      - "9120:9120" # Prometheus metrics
      - "1099:80"
    # For all available environment variables and explanations, see https://github.com/kimdre/doco-cd/wiki/App-Settings
    # env_file:
    #   - .env
    environment:
      TZ: America/New_York
      #GIT_ACCESS_TOKEN: 
      HTTP_PORT: 80
      WEBHOOK_SECRET_FILE: /run/secrets/webhook_secret
      SOPS_AGE_KEY_FILE: /run/secrets/sops_age_key
      API_SECRET_FILE: /run/secrets/api_key
      #<<: *poll-config  # Uncomment this line to use the poll configuration from above (the `x-poll-config` section).
    networks: 
      backbone:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /persist/prod/base/doco-cd:/data
    # healthcheck:
      # test: [ "CMD", "curl", "-f", "http://localhost:80/v1/health" ]  # Also change the port here if you change the default HTTP_PORT env var
      # start_period: 15s
      # interval: 30s
      # timeout: 5s
      # retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.doco.rule=Host(`doco.stickpile.net`)"
      - "traefik.http.routers.doco.entrypoints=websecure"
      - "traefik.http.routers.doco.tls.certresolver=httpsResolve"
      - "traefik.http.services.doco.loadbalancer.server.port=80"
    #  - "traefik.http.routers.doco.middlewares=middlewares-authentik@file"
    # deploy:
    #   replicas: 1
    #   placement:
    #     constraints:
    #       - node.role == manager
    secrets:
      - sops_age_key
      - git_access_token
      - webhook_secret
      - api_key



secrets:
  sops_age_key: # Preferably detatch this from any public git repos. This is an immutable mount on every host.
    file: /stateful/sys-data/secrets/sops_age_key.txt
  git_access_token: 
    file: /stateful/sys-data/secrets/git-pat.txt
  webhook_secret: 
    file: /stateful/sys-data/secrets/ws-secret.txt
  api_key: 
    file: /stateful/sys-data/secrets/doco-cd_api-key.txt
  # git_access_token:
  #   external: true
  # webhook_secret:
  #   external: true

networks:
  backbone: # For external containers.
    name: traefik_backbone
    external: true